export const FETCH_DEPT_SUCCESS = "FETCH_DEPT_SUCCESS";
export const FETCH_DEPT_FAILURE = "FETCH_DEPT_FAILURE";
export const FETCH_DEPT_REQUEST = "FETCH_DEPT_REQUEST";

export const CREATE_DEPT_REQUEST = "CREATE_DEPT_REQUEST";
export const CREATE_DEPT_SUCCESS = "CREATE_DEPT_SUCCESS";
export const CREATE_DEPT_FAILURE = "CREATE_DEPT_FAILURE";

export const PATCH_DEPT_REQUEST = "PATCH_DEPT_REQUEST";
export const PATCH_DEPT_SUCCESS = "PATCH_DEPT_SUCCESS";
export const PATCH_DEPT_FAILURE = "PATCH_DEPT_FAILURE";

export const DELETE_DEPT_REQUEST = "DELETE_DEPT_REQUEST";
export const DELETE_DEPT_SUCCESS = "DELETE_DEPT_SUCCESS";
export const DELETE_DEPT_FAILURE = "DELETE_DEPT_FAILURE";
